steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set project cedar-scope-364112 && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy--log-http --verbosity=debug']

timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY